name: Unit Tests

on: [push, pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest pytest-cov pytest-html flake8

            - name: Run Unit Tests
              run: python3 -m pytest --cov-report=xml --cov=. --html=report.html -v

            - name: Lint
              run: flake8

            - name: Upload corevage to Codecov
              uses: codecov/codecov-action@v1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                file: ./coverage.xml
                flags: unittests
                fail_ci_if_error: true
                verbose: true

            - name: Export Unit Tests Artifact
              uses: actions/upload-artifact@v2
              with:
                name: unit-tests-report
                path: ./report.html
